import * as vscode from 'vscode';
import { Coordinator } from './coordinator';
import { DiagnosticsManager } from './diagnostics';
import { CodeActionsProvider } from './codeActions';
import { GeminiService } from './geminiService';
import { SemgrepRunner } from './semgrepRunner';
import { MetricsManager } from './metricsManager';

let coordinator: Coordinator;
let diagnosticsManager: DiagnosticsManager;
let codeActionsProvider: CodeActionsProvider;
let geminiService: GeminiService;
let metricsManager: MetricsManager;

// Enhance issues with AI explanations
async function enhanceIssuesWithAI(issues: any[]): Promise<any[]> {
	if (!issues || issues.length === 0) {
		return issues;
	}

	console.log(`🤖 Enhancing ${issues.length} issues with AI explanations...`);
	const enhancedIssues = [];

	for (const issue of issues) {
		try {
			// Get AI explanation
			const explanation = await geminiService.explainIssue(issue);
			
			const enhancedIssue = {
				...issue,
				explanation: explanation ? explanation.explanation : undefined,
				aiSeverity: explanation ? explanation.severity : issue.severity,
				fix: explanation ? explanation.fix : issue.fix,
				cwe: explanation ? explanation.cwe : issue.cwe,
				hasAIExplanation: !!explanation
			};

			enhancedIssues.push(enhancedIssue);
			console.log(`✅ Enhanced issue ${issue.ruleId} with AI explanation`);
		} catch (error) {
			console.warn(`⚠️ Failed to enhance issue ${issue.ruleId}:`, error);
			// Add the original issue if AI enhancement fails
			enhancedIssues.push({
				...issue,
				hasAIExplanation: false
			});
		}
	}

	console.log(`🎯 Enhanced ${enhancedIssues.filter(i => i.hasAIExplanation).length}/${issues.length} issues with AI`);
	return enhancedIssues;
}

// Fallback security prompt enhancement when AI is unavailable
function createFallbackSecurityPrompt(originalPrompt: string): string {
	// Create a practical, enhanced prompt based on the user's request
	let enhancedPrompt = originalPrompt;
	
	// Add security context based on common patterns
	if (originalPrompt.toLowerCase().includes('login') || originalPrompt.toLowerCase().includes('auth')) {
		enhancedPrompt = `Create a secure ${originalPrompt.toLowerCase()} system with proper input validation, bcrypt password hashing, JWT tokens, rate limiting for brute force protection, and secure session management. Include error handling that doesn't leak sensitive information.`;
	} else if (originalPrompt.toLowerCase().includes('api') || originalPrompt.toLowerCase().includes('endpoint')) {
		enhancedPrompt = `Create a secure ${originalPrompt.toLowerCase()} with input validation, authentication middleware, rate limiting, parameterized database queries, proper error handling, and comprehensive logging. Use environment variables for all secrets.`;
	} else if (originalPrompt.toLowerCase().includes('database') || originalPrompt.toLowerCase().includes('query')) {
		enhancedPrompt = `Create a secure ${originalPrompt.toLowerCase()} using parameterized queries to prevent SQL injection, input validation, proper error handling, and connection pooling. Include audit logging and ensure no sensitive data is logged.`;
	} else if (originalPrompt.toLowerCase().includes('upload') || originalPrompt.toLowerCase().includes('file')) {
		enhancedPrompt = `Create a secure ${originalPrompt.toLowerCase()} system with file type validation, size limits, virus scanning, secure file storage, and proper access controls. Validate all file metadata and use content-type verification.`;
	} else {
		enhancedPrompt = `${originalPrompt}. Ensure the implementation includes comprehensive input validation, secure error handling, proper authentication/authorization, environment variables for secrets, parameterized database queries, rate limiting, and security logging.`;
	}

	return `# 🛡️ Security-Enhanced Prompt

## 📋 Copy-Paste Ready Prompt

\`\`\`
${enhancedPrompt}
\`\`\`

## 📝 Original Request
> ${originalPrompt}

## 🛡️ Security Features Included
- ✅ **Input Validation** - Prevent malicious input
- ✅ **Secure Authentication** - Proper user verification
- ✅ **SQL Injection Prevention** - Parameterized queries
- ✅ **Secret Management** - Environment variables
- ✅ **Error Handling** - No information leakage
- ✅ **Rate Limiting** - Prevent abuse
- ✅ **Security Logging** - Audit trail
- ✅ **Dependency Security** - Updated packages

## 🚀 How to Use
1. **Copy the enhanced prompt** from the code block above
2. **Paste it into your AI assistant** (ChatGPT, Claude, Copilot, etc.)
3. **Get secure, production-ready code** with built-in security best practices

---
*🛡️ Generated by Secure Code Assistant (Template Mode)*`;
}

export function activate(context: vscode.ExtensionContext) {
	console.log('Activating Secure Code Assistant...');

	// Initialize core components
	coordinator = Coordinator.getInstance(context);
	diagnosticsManager = new DiagnosticsManager();
	geminiService = new GeminiService();
	metricsManager = MetricsManager.getInstance(context);
	codeActionsProvider = new CodeActionsProvider(coordinator, diagnosticsManager, metricsManager);

	// Register commands
	registerCommands(context);
	
	// Register providers
	registerProviders(context);
	
	// Set up event listeners
	setupEventListeners(context);

	console.log('Secure Code Assistant activated successfully!');
}

function registerCommands(context: vscode.ExtensionContext) {
	// Toggle reviewer command
	const toggleReviewer = vscode.commands.registerCommand('secureCodeAssistant.toggleReviewer', () => {
		const isEnabled = coordinator.toggle();
		const message = isEnabled ? 'Security reviewer enabled' : 'Security reviewer disabled';
		vscode.window.showInformationMessage(message);
		
		if (!isEnabled) {
			diagnosticsManager.clearAllDiagnostics();
		}
	});

	// Enhance prompt command
	const enhancePrompt = vscode.commands.registerCommand('secureCodeAssistant.enhancePrompt', async (selectedText?: string) => {
		// Use selected text if provided (from context menu), otherwise ask for input
		let userPrompt = selectedText;
		
		if (!userPrompt) {
			userPrompt = await vscode.window.showInputBox({
				prompt: 'Enter your prompt to enhance with security requirements...',
				placeHolder: 'e.g., Create a login function for my web app',
				value: '' // Start with empty value
			});
		}

		if (!userPrompt || userPrompt.trim() === '') {
			vscode.window.showWarningMessage('No prompt provided to enhance');
			return;
		}

		try {
			vscode.window.showInformationMessage('Enhancing prompt with security requirements...');
			console.log('Enhancing prompt:', userPrompt);
			
			const enhancedPrompt = await geminiService.enhancePrompt(userPrompt.trim());
			console.log('Enhanced prompt result:', enhancedPrompt);
			
			// Always show ONLY the enhanced prompt (no code generation)
			const doc = await vscode.workspace.openTextDocument({
				content: `# 🛡️ Security-Enhanced Prompt

## 📋 Enhanced Prompt (Copy-Paste Ready)

\`\`\`
${enhancedPrompt}
\`\`\`

## 📝 Original Request
> ${userPrompt}

## 🔐 Why This Matters
This enhanced prompt adds focused security guidance without generating code. Use it in any AI coding assistant to obtain implementation that already considers security best practices.

---
*🛡️ Generated by Secure Code Assistant (Prompt-Only Mode)*`,
				language: 'markdown'
			});
			await vscode.window.showTextDocument(doc);
			vscode.window.showInformationMessage('✅ Enhanced security prompt ready (no code generated).');
		} catch (error) {
			console.error('Prompt enhancement failed:', error);
			
			// Fallback: provide manual security enhancement
			const fallbackEnhancement = createFallbackSecurityPrompt(userPrompt);
			
			const doc = await vscode.workspace.openTextDocument({
				content: fallbackEnhancement,
				language: 'markdown'
			});
			
			await vscode.window.showTextDocument(doc);
			vscode.window.showWarningMessage(
				`Using fallback template. AI error: ${error}`, 
				'Configure AI', 
				'Get API Key'
			).then(selection => {
				if (selection === 'Configure AI') {
					vscode.commands.executeCommand('secureCodeAssistant.configureApiKey');
				} else if (selection === 'Get API Key') {
					vscode.env.openExternal(vscode.Uri.parse('https://aistudio.google.com/app/apikey'));
				}
			});
		}
	});

	// Manual scan command for testing
	const scanCurrentFile = vscode.commands.registerCommand('secureCodeAssistant.scanCurrentFile', async () => {
		const activeEditor = vscode.window.activeTextEditor;
		if (!activeEditor) {
			vscode.window.showWarningMessage('No active file to scan');
			return;
		}

		try {
			vscode.window.showInformationMessage('Starting security scan...');
			console.log('Manual scan - File:', activeEditor.document.fileName);
			console.log('Manual scan - Workspace:', vscode.workspace.workspaceFolders?.[0]?.uri.fsPath);
			
			const startTime = Date.now();
			const issues = await SemgrepRunner.runSemgrep(activeEditor.document.fileName);
			const scanDuration = Date.now() - startTime;
			console.log('Manual scan - Issues found:', issues.length);
			
			// Record metrics
			metricsManager.recordScan(activeEditor.document.fileName, issues, 'manual', scanDuration);
			
			coordinator.recordIssues(activeEditor.document.fileName, issues);
			diagnosticsManager.applyDiagnosticsForFile(activeEditor.document, issues);
			
			const message = issues.length > 0 
				? `Found ${issues.length} security issue(s)`
				: 'No security issues found';
			vscode.window.showInformationMessage(message);
		} catch (error) {
			console.error('Manual scan failed:', error);
			vscode.window.showErrorMessage(`Scan failed: ${error}`);
		}
	});

	// Generate security report command
	const generateReport = vscode.commands.registerCommand('secureCodeAssistant.generateReport', async () => {
		try {
			const allIssues = coordinator.getAllIssues();
			
			if (allIssues.size === 0) {
				vscode.window.showInformationMessage('No security issues found to report.');
				return;
			}

			const report = await geminiService.generateSecurityReport(allIssues);
			
			// Save report to workspace
			const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
			if (workspaceFolder) {
				const reportPath = vscode.Uri.joinPath(workspaceFolder.uri, 'SECURITY_REPORT.md');
				await vscode.workspace.fs.writeFile(reportPath, Buffer.from(report, 'utf8'));
				
				// Open the report
				const doc = await vscode.workspace.openTextDocument(reportPath);
				await vscode.window.showTextDocument(doc);
				
				vscode.window.showInformationMessage('Security report generated successfully!');
			} else {
				// Show in new document if no workspace
				const doc = await vscode.workspace.openTextDocument({
					content: report,
					language: 'markdown'
				});
				await vscode.window.showTextDocument(doc);
			}
		} catch (error) {
			vscode.window.showErrorMessage(`Failed to generate report: ${error}`);
		}
	});

	// Metrics report command
	const metricsReport = vscode.commands.registerCommand('secureCodeAssistant.showMetrics', async () => {
		try {
			const report = metricsManager.generateMetricsReport();
			
			// Show in new document
			const doc = await vscode.workspace.openTextDocument({
				content: report,
				language: 'markdown'
			});
			await vscode.window.showTextDocument(doc);
			
			vscode.window.showInformationMessage('Security metrics report generated!');
		} catch (error) {
			vscode.window.showErrorMessage(`Failed to generate metrics report: ${error}`);
		}
	});

	// Enhance prompt from selection command (for context menu)
	const enhancePromptFromSelection = vscode.commands.registerCommand('secureCodeAssistant.enhancePromptFromSelection', async () => {
		const activeEditor = vscode.window.activeTextEditor;
		if (!activeEditor) {
			vscode.window.showWarningMessage('No active editor found');
			return;
		}

		const selection = activeEditor.selection;
		const selectedText = activeEditor.document.getText(selection);
		
		if (!selectedText || selectedText.trim() === '') {
			vscode.window.showWarningMessage('No text selected. Please select some text to enhance as a prompt.');
			return;
		}

		// Use the main enhance prompt command with the selected text
		await vscode.commands.executeCommand('secureCodeAssistant.enhancePrompt', selectedText.trim());
	});

	// Command to apply fix and record metrics
	const applyFixWithMetrics = vscode.commands.registerCommand('secureCodeAssistant.applyFixWithMetrics', 
		async (fileName: string, issue: any, workspaceEdit: vscode.WorkspaceEdit) => {
			try {
				const success = await vscode.workspace.applyEdit(workspaceEdit);
				metricsManager.recordFix(fileName, issue, 'quick-fix', success);
				
				if (success) {
					vscode.window.showInformationMessage(`Security fix applied: ${issue.ruleId}`);
				} else {
					vscode.window.showWarningMessage(`Failed to apply security fix: ${issue.ruleId}`);
				}
			} catch (error) {
				console.error('Fix application failed:', error);
				metricsManager.recordFix(fileName, issue, 'quick-fix', false);
				vscode.window.showErrorMessage(`Error applying fix: ${error}`);
			}
		}
	);

	// Command to reload/test API key configuration
	const reloadApiKey = vscode.commands.registerCommand('secureCodeAssistant.reloadApiKey', async () => {
		try {
			vscode.window.showInformationMessage('🔄 Reloading AI configuration...');
			
			// Reinitialize the Gemini service
			geminiService = new GeminiService();
			
			// Test with a simple prompt
			const testResult = await geminiService.enhancePrompt('Test connection');
			if (testResult !== 'Test connection') {
				vscode.window.showInformationMessage('✅ AI service is working correctly!');
			} else {
				vscode.window.showWarningMessage('⚠️ AI service loaded but test failed. Check console for details.');
			}
		} catch (error) {
			vscode.window.showErrorMessage(`❌ Failed to reload AI configuration: ${error}`);
		}
	});

	// Command to configure API key
	const configureApiKey = vscode.commands.registerCommand('secureCodeAssistant.configureApiKey', async () => {
		const apiKey = await vscode.window.showInputBox({
			prompt: 'Enter your Google Gemini API Key',
			placeHolder: 'AIza...',
			password: true,
			validateInput: (value) => {
				if (!value || value.trim().length === 0) {
					return 'API key cannot be empty';
				}
				if (!value.startsWith('AIza')) {
					return 'Google API keys typically start with "AIza"';
				}
				return null;
			}
		});

		if (apiKey) {
			try {
				// Store in workspace settings
				const config = vscode.workspace.getConfiguration('secureAssistant');
				await config.update('geminiApiKey', apiKey.trim(), vscode.ConfigurationTarget.Workspace);
				
				// Reinitialize the service
				geminiService = new GeminiService();
				
				vscode.window.showInformationMessage('✅ Gemini API key configured successfully! AI-powered features are now available.');
				
				// Test the service
				const testResult = await geminiService.enhancePrompt('Test prompt');
				if (testResult !== 'Test prompt') {
					vscode.window.showInformationMessage('🤖 AI service is working correctly!');
				} else {
					vscode.window.showWarningMessage('⚠️ API key saved but AI service test failed. Please check your key.');
				}
			} catch (error) {
				vscode.window.showErrorMessage(`Failed to configure API key: ${error}`);
			}
		}
	});

	context.subscriptions.push(toggleReviewer, enhancePrompt, enhancePromptFromSelection, scanCurrentFile, generateReport, metricsReport, applyFixWithMetrics, configureApiKey, reloadApiKey);
}

function registerProviders(context: vscode.ExtensionContext) {
	// Register code actions provider
	const codeActionProvider = vscode.languages.registerCodeActionsProvider(
		{ scheme: 'file' },
		codeActionsProvider,
		{
			providedCodeActionKinds: [vscode.CodeActionKind.QuickFix]
		}
	);

	// Register hover provider for security explanations
	const hoverProvider = vscode.languages.registerHoverProvider(
		{ scheme: 'file' },
		{
			async provideHover(document, position, token) {
				const issues = coordinator.getIssuesForFile(document.fileName);
				const currentLine = position.line + 1; // Convert to 1-based
				
				const relevantIssue = issues.find(issue => 
					Math.abs(issue.line - currentLine) <= 2 // Allow some tolerance
				);
				
				if (!relevantIssue) {
					return null;
				}

				try {
					const contents = new vscode.MarkdownString();
					contents.appendMarkdown(`**Security Issue: ${relevantIssue.ruleId}**\n\n`);
					
					// Use cached AI explanation if available
					if (relevantIssue.hasAIExplanation && relevantIssue.explanation) {
						contents.appendMarkdown(`**AI Severity:** ${relevantIssue.aiSeverity}\n\n`);
						contents.appendMarkdown(`**AI Explanation:** ${relevantIssue.explanation}\n\n`);
						contents.appendMarkdown(`**Suggested Fix:** ${relevantIssue.fix}\n\n`);
						if (relevantIssue.cwe) {
							contents.appendMarkdown(`**CWE:** ${relevantIssue.cwe}\n\n`);
						}
						contents.appendMarkdown(`*🤖 Enhanced with AI*`);
					} else {
						// Fallback: try to get AI explanation on-demand
						const explanation = await geminiService.explainIssue(relevantIssue);
						if (explanation) {
							contents.appendMarkdown(`**AI Severity:** ${explanation.severity}\n\n`);
							contents.appendMarkdown(`**AI Explanation:** ${explanation.explanation}\n\n`);
							contents.appendMarkdown(`**Suggested Fix:** ${explanation.fix}\n\n`);
							if (explanation.cwe) {
								contents.appendMarkdown(`**CWE:** ${explanation.cwe}\n\n`);
							}
							contents.appendMarkdown(`*🤖 AI Analysis*`);
						} else {
							// Basic information without AI
							contents.appendMarkdown(`**Severity:** ${relevantIssue.severity}\n\n`);
							contents.appendMarkdown(`**Message:** ${relevantIssue.message}\n\n`);
							if (relevantIssue.cwe) {
								contents.appendMarkdown(`**CWE:** ${relevantIssue.cwe}\n\n`);
							}
							contents.appendMarkdown(`*⚠️ AI analysis unavailable*`);
						}
					}
					
					return new vscode.Hover(contents);
				} catch (error) {
					console.error('Failed to get hover explanation:', error);
					// Return basic hover as fallback
					const contents = new vscode.MarkdownString();
					contents.appendMarkdown(`**Security Issue: ${relevantIssue.ruleId}**\n\n`);
					contents.appendMarkdown(`**Message:** ${relevantIssue.message}\n\n`);
					return new vscode.Hover(contents);
				}
			}
		}
	);

	context.subscriptions.push(codeActionProvider, hoverProvider);
}

function setupEventListeners(context: vscode.ExtensionContext) {
	// Scan on file save
	const onSave = vscode.workspace.onDidSaveTextDocument(async (document) => {
		console.log('File saved:', document.fileName);
		
		if (!coordinator.isEnabled()) {
			console.log('Coordinator is disabled, skipping scan');
			return;
		}

		const config = vscode.workspace.getConfiguration('secureAssistant');
		const scanOnSave = config.get<boolean>('scanOnSave', true);
		
		if (!scanOnSave) {
			console.log('Scan on save is disabled');
			return;
		}

		// Only scan supported file types
		const supportedExtensions = ['.js', '.ts', '.py', '.java', '.go', '.php', '.rb', '.c', '.cpp', '.cs'];
		const fileExtension = document.fileName.substring(document.fileName.lastIndexOf('.'));
		
		if (!supportedExtensions.includes(fileExtension)) {
			console.log('Unsupported file type:', fileExtension);
			return;
		}

		try {
			console.log('Starting Semgrep scan for:', document.fileName);
			console.log('File extension:', document.fileName.substring(document.fileName.lastIndexOf('.')));
			console.log('Workspace folders:', vscode.workspace.workspaceFolders?.map(f => f.uri.fsPath));
			
			const startTime = Date.now();
			const issues = await SemgrepRunner.runSemgrep(document.fileName);
			const scanDuration = Date.now() - startTime;
			console.log('SemgrepRunner returned:', issues.length, 'security issues');
			console.log('Issues:', issues.map(i => ({ line: i.line, ruleId: i.ruleId, message: i.message })));
			
			// Record metrics
			metricsManager.recordScan(document.fileName, issues, 'auto-save', scanDuration);
			
			coordinator.recordIssues(document.fileName, issues);
			diagnosticsManager.applyDiagnosticsForFile(document, issues);
			
			const message = issues.length > 0 
				? `Found ${issues.length} security issue(s) in ${document.fileName.split('/').pop()}`
				: `No security issues found in ${document.fileName.split('/').pop()}`;
			
			vscode.window.showInformationMessage(message);
		} catch (error) {
			console.error('Failed to scan file:', error);
			vscode.window.showErrorMessage(`Security scan failed: ${error}`);
		}
	});

	// Clear diagnostics when reviewer is disabled
	coordinator.on('reviewerDisabled', () => {
		diagnosticsManager.clearAllDiagnostics();
	});

	// Clean up diagnostics when files are closed
	const onClose = vscode.workspace.onDidCloseTextDocument((document) => {
		diagnosticsManager.clearDiagnosticsForFile(document.uri);
	});

	context.subscriptions.push(onSave, onClose);
}

export function deactivate() {
	if (coordinator) {
		coordinator.dispose();
	}
	if (diagnosticsManager) {
		diagnosticsManager.dispose();
	}
	if (metricsManager) {
		metricsManager.dispose();
	}
}
